
USE SocialMedia
GO

IF NOT EXISTS(SELECT * FROM sys.SERVER_PRINCIPALS WHERE NAME = 'SMUser')
BEGIN
	CREATE LOGIN SMUser WITH PASSWORD=N'SmPA$$06500',DEFAULT_DATABASE=SocialMedia
END

IF NOT EXISTS(SELECT * FROM sys.DATABASE_PRINCIPALS WHERE name = 'SMUser')
BEGIN
	EXEC sp_addUser 'SMUser', 'SMUser', 'db_owner';
END